services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes: [mongo-data:/data/db]
    ports: ["27017:27017"]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes: [redis-data:/data]
    ports: ["6379:6379"]

  api:
    build: .
    env_file: .env
    depends_on: [mongo, redis]
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    env_file: .env
    depends_on: [mongo, redis]
    command: celery -A app.workers.celery_app.celery worker -l INFO -Q default,ocr,threat,report

  beat:
    build: .
    env_file: .env
    depends_on: [redis]
    command: celery -A app.workers.celery_app.celery beat -l INFO

  flower:
    build: .
    env_file: .env
    depends_on: [redis]
    ports: ["5555:5555"]
    command: celery -A app.workers.celery_app.celery flower --port=5555

volumes:
  mongo-data:
  redis-data:
